[package]
name = "funai-genesis"
version = "0.1.0"
authors = ["Matthew Little <matthew@blockstack.com>"]
edition = "2018"
resolver = "2"

[dependencies]
libflate = "1.0.3"

[lib]
name = "funai_genesis"
path = "src/lib.rs"

[build-dependencies]
libflate = "1.0.3"
sha2 = { version = "0.10" }
