[node]
working_dir = "/llm_chain_local"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
seed = ""
local_peer_seed = ""
miner = true
wait_time_for_microblocks = 1000
miner_endpoint = "http://127.0.0.1:20443"

[burnchain]
chain = "bitcoin"
mode = "xenon"
peer_host = ""
username = ""
password = ""
rpc_port = 18443
peer_port = 18444
wallet_name = "miner"

[connection_options]
block_proposal_token = "123456"

[miner]
mining_key = ""

[[events_observer]]
endpoint = "127.0.0.1:30000"
retry_count = 255
include_data_events = false
events_keys = ["*","funaidb","block_proposal"]

[[ustx_balance]]
address = "ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2"
amount = 10000000000000000

[[ustx_balance]]
address = "ST319CF5WV77KYR1H3GT0GZ7B8Q4AQPY42ETP1VPF"
amount = 10000000000000000

[[ustx_balance]]
address = "ST221Z6TDTC5E0BYR2V624Q2ST6R0Q71T78WTAX6H"
amount = 10000000000000000

[[ustx_balance]]
address = "ST2TFVBMRPS5SSNP98DQKQ5JNB2B6NZM91C4K3P7B"
amount = 10000000000000000

[[ustx_balance]]
address = "ST6ZMM0CX01734YMS6Q7SPJHQR9GMQPSBH6RP8RV"
amount = 90000000000000000